</$objtype/mkfile

BIN=/rc/bin
TARG=chat

MAN=/sys/man/1
MANFILES=${TARG:%=%.man}

none:VQ:
	echo usage: mk install, or mk man

$BIN/%:	%.rc
	cp $stem.rc $BIN/$stem

%.install:V:	$BIN/%

install:V:
	for(i in $TARG)
		mk $MKFLAGS $i.install

%.man:	$MAN/$stem
	cp $stem.man $MAN/$stem

man:V:	$MANFILES
